### GET request with a header
GET http://localhost:8080
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = Dm79PRFLeiyxizakPYbNrvqdxLWAdmw0USGEfxVwpo8zHeEBOAzIDyB_HhmcuALFDqv5mpyu6Yy5Rg8ZZ0XgHCQVwLkGJIAz

### Send GET request with json body
GET http://localhost:8080/csrfToken
Content-Type: application/json